# Generated by Django 5.2.5 on 2025-09-26 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigosFonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo_id', models.IntegerField(unique=True)),
                ('menu', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo_bruto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtigoProcessado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_trecho', models.IntegerField()),
                ('conteudo_limpo', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='tools.artigosfonte')),
            ],
            options={
                'unique_together': {('fonte', 'indice_trecho')},
            },
        ),
    ]
